//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataExtensibilityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : BusinessObject<Customer>
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
    	private System.Guid _customerId;
    	public System.Guid CustomerId
    	{
    		get { return GetProperty("CustomerId", _customerId); }
    		set { SetProperty("CustomerId", ref _customerId, value); }
    	}
    	private string _firstName;
    	public string FirstName
    	{
    		get { return GetProperty("FirstName", _firstName); }
    		set { SetProperty("FirstName", ref _firstName, value); }
    	}
    	private string _lastName;
    	public string LastName
    	{
    		get { return GetProperty("LastName", _lastName); }
    		set { SetProperty("LastName", ref _lastName, value); }
    	}
    	private string _address;
    	public string Address
    	{
    		get { return GetProperty("Address", _address); }
    		set { SetProperty("Address", ref _address, value); }
    	}
    	private string _postalCode;
    	public string PostalCode
    	{
    		get { return GetProperty("PostalCode", _postalCode); }
    		set { SetProperty("PostalCode", ref _postalCode, value); }
    	}
    	private string _city;
    	public string City
    	{
    		get { return GetProperty("City", _city); }
    		set { SetProperty("City", ref _city, value); }
    	}
    	private string _country;
    	public string Country
    	{
    		get { return GetProperty("Country", _country); }
    		set { SetProperty("Country", ref _country, value); }
    	}
    	private string _telephone;
    	public string Telephone
    	{
    		get { return GetProperty("Telephone", _telephone); }
    		set { SetProperty("Telephone", ref _telephone, value); }
    	}
    	private string _email;
    	public string Email
    	{
    		get { return GetProperty("Email", _email); }
    		set { SetProperty("Email", ref _email, value); }
    	}
    
    	private ICollection<Order> _orders;
    	public virtual ICollection<Order> Orders
    	{
    		get { return GetProperty("Orders", _orders); }
    		set { SetProperty("Orders", ref _orders, value); }
    	}
    }
}
