//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataExtensibilityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup : BusinessObject<Lookup>
    {
    	private System.Guid _lookupId;
    	public System.Guid LookupId
    	{
    		get { return GetProperty("LookupId", _lookupId); }
    		set { SetProperty("LookupId", ref _lookupId, value); }
    	}
    	private string _description;
    	public string Description
    	{
    		get { return GetProperty("Description", _description); }
    		set { SetProperty("Description", ref _description, value); }
    	}
    }
}
