//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataExtensibilityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail : BusinessObject<OrderDetail>
    {
    	private System.Guid _orderId;
    	public System.Guid OrderId
    	{
    		get { return GetProperty("OrderId", _orderId); }
    		set { SetProperty("OrderId", ref _orderId, value); }
    	}
    	private System.Guid _productId;
    	public System.Guid ProductId
    	{
    		get { return GetProperty("ProductId", _productId); }
    		set { SetProperty("ProductId", ref _productId, value); }
    	}
    	private Nullable<decimal> _unitPrice;
    	public Nullable<decimal> UnitPrice
    	{
    		get { return GetProperty("UnitPrice", _unitPrice); }
    		set { SetProperty("UnitPrice", ref _unitPrice, value); }
    	}
    	private Nullable<decimal> _quantity;
    	public Nullable<decimal> Quantity
    	{
    		get { return GetProperty("Quantity", _quantity); }
    		set { SetProperty("Quantity", ref _quantity, value); }
    	}
    	private Nullable<decimal> _discount;
    	public Nullable<decimal> Discount
    	{
    		get { return GetProperty("Discount", _discount); }
    		set { SetProperty("Discount", ref _discount, value); }
    	}
    
    	private Order _order;
    	public virtual Order Order
    	{
    		get { return GetProperty("Order", _order); }
    		set { SetProperty("Order", ref _order, value); }
    	}
    	private Product _product;
    	public virtual Product Product
    	{
    		get { return GetProperty("Product", _product); }
    		set { SetProperty("Product", ref _product, value); }
    	}
    }
}
