//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataExtensibilityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order : BusinessObject<Order>
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
    	private System.Guid _orderId;
    	public System.Guid OrderId
    	{
    		get { return GetProperty("OrderId", _orderId); }
    		set { SetProperty("OrderId", ref _orderId, value); }
    	}
    	private System.Guid _customerId;
    	public System.Guid CustomerId
    	{
    		get { return GetProperty("CustomerId", _customerId); }
    		set { SetProperty("CustomerId", ref _customerId, value); }
    	}
    	private System.DateTime _orderDate;
    	public System.DateTime OrderDate
    	{
    		get { return GetProperty("OrderDate", _orderDate); }
    		set { SetProperty("OrderDate", ref _orderDate, value); }
    	}
    	private Nullable<System.DateTime> _shippedDate;
    	public Nullable<System.DateTime> ShippedDate
    	{
    		get { return GetProperty("ShippedDate", _shippedDate); }
    		set { SetProperty("ShippedDate", ref _shippedDate, value); }
    	}
    
    	private Customer _customer;
    	public virtual Customer Customer
    	{
    		get { return GetProperty("Customer", _customer); }
    		set { SetProperty("Customer", ref _customer, value); }
    	}
    	private ICollection<OrderDetail> _orderDetails;
    	public virtual ICollection<OrderDetail> OrderDetails
    	{
    		get { return GetProperty("OrderDetails", _orderDetails); }
    		set { SetProperty("OrderDetails", ref _orderDetails, value); }
    	}
    }
}
