//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataExtensibilityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : BusinessObject<Product>
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
    	private System.Guid _productId;
    	public System.Guid ProductId
    	{
    		get { return GetProperty("ProductId", _productId); }
    		set { SetProperty("ProductId", ref _productId, value); }
    	}
    	private string _name;
    	public string Name
    	{
    		get { return GetProperty("Name", _name); }
    		set { SetProperty("Name", ref _name, value); }
    	}
    	private string _description;
    	public string Description
    	{
    		get { return GetProperty("Description", _description); }
    		set { SetProperty("Description", ref _description, value); }
    	}
    	private Nullable<decimal> _unitPrice;
    	public Nullable<decimal> UnitPrice
    	{
    		get { return GetProperty("UnitPrice", _unitPrice); }
    		set { SetProperty("UnitPrice", ref _unitPrice, value); }
    	}
    
    	private ICollection<OrderDetail> _orderDetails;
    	public virtual ICollection<OrderDetail> OrderDetails
    	{
    		get { return GetProperty("OrderDetails", _orderDetails); }
    		set { SetProperty("OrderDetails", ref _orderDetails, value); }
    	}
    }
}
