ALTER TABLE [dbo].[Lookup]
    ADD CONSTRAINT [PK_Lookup] PRIMARY KEY CLUSTERED ([LookupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

